### ISSUE TITLE
Ansible fails to parse the script as inventory 

### ISSUE THREAD

**Issue by R1VR** [Cloud-Temple/yaani#6]
Ansible fails to parse the script as inventory when we have entries in /dcim/devices with blank name

Netbox allows the creation of devices with a blank name field
Appears like this on netbox in devices category:

<img width="286" alt="Capture d’écran 2019-08-21 à 11 44 09" src="https://user-images.githubusercontent.com/31739120/63421530-06d6c900-c409-11e9-86e0-fce741c6ada8.png">

When launching a basic playbook with yaani as inventory source:

`ansible-playbook -i /root/yaani/yaani.py test.yml`

It throws the following error

``` 
[WARNING]:  * Failed to parse /root/yaani/yaani.py with script plugin: Invalid empty host name provided: None

 [WARNING]:  * Failed to parse /root/yaani/yaani.py with ini plugin: /root/yaani/yaani.py:3: Expected key=value host variable
assignment, got: __future__

 [WARNING]: Unable to parse /root/yaani/yaani.py as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
```

If we delete the device with the blank name or we give it a name the playbook runs without any errors.

Something should be added to handle devices ( and maybe other entries like racks ) with blank names.

**Comment by a-delannoy** [comment]
Hello, 

Thanks for the report :) May I ask you to provide me with the configuration file you used in order for me to reproduce this issue ?

**Comment by R1VR** [comment]
Of course

Below : netbox.yml

```
netbox:
  api:
    api_url: "<url>"

  import:
    devices:
      filter: role_id=4&role_id=3
      group_by:
        - tags

      group_prefix: 'dev_'

      host_vars:
        ansible_host: primary_ip.address
        id_ansible_host: id
        status: status.value
        current_os_version: custom_fields.os_version
        platform: platform.slug
        model: device_type.model
        virtual_chassis: custom_fields.virtual_chassis
```

Cheers

**Comment by a-delannoy** [comment]
The problem has been identified and is being corrected.

**Comment by R1VR** [comment]
The issue has been solved.

Ansible does not fail anymore when working with devices containing blank names

Thanks for the fix
